name: CI
on: [push]
jobs:
  build:
    if: github.repository != 'js-fn/template'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run cover
      - uses: codecov/codecov-action@v1.0.6
        with:
          # User defined upload name. Visible in Codecov UI
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: c6348e20-1b3a-4b59-a8c1-8862e51b099d

    env:
      CI: true
